# TRI Intermediate and Final Output

In [18]:
%run TRI.py

/Users/alexisvstarr/anaconda/lib/python3.6/site-packages/IPython/core/magics/execution.py:728: DtypeWarning: Columns (121,122) have mixed types. Specify dtype option on import or set low_memory=False.
  exit_ignore=exit_ignore)
/Users/alexisvstarr/anaconda/lib/python3.6/site-packages/IPython/core/magics/execution.py:728: DtypeWarning: Columns (127,128) have mixed types. Specify dtype option on import or set low_memory=False.
  exit_ignore=exit_ignore)
/Users/alexisvstarr/anaconda/lib/python3.6/site-packages/IPython/core/magics/execution.py:728: DtypeWarning: Columns (133,134) have mixed types. Specify dtype option on import or set low_memory=False.
  exit_ignore=exit_ignore)
/Users/alexisvstarr/csra/LCI-Primer/TRI.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  #Link Basis of Estimate to Data Reliability Scores
/Users/alexisvstarr/csra/LCI-Primer/TRI.py:139: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/alexisvstarr/csra/LCI-Primer/TRI.py:140: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  #drop old amount and units

Prints dictionary containing imported fields for visual QC. Keys are presented in red.

In [19]:
for k, v in import_dict.items():
    print('\x1b[31m\"%s\"\x1b[0m:%s' % (k, v))

"fug":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'TOTAL FUGITIVE AIR EMISSIONS', 'FUGITIVE OR NON-POINT AIR EMISSIONS - BASIS OF ESTIMATE']
"stack":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'TOTAL STACK AIR EMISSIONS', 'STACK OR POINT AIR EMISSIONS - BASIS OF ESTIMATE']
"streamA":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'TOTAL DISCHARGES TO STREAM A', 'DISCHARGES TO STREAM A - BASIS OF ESTIMATE']
"streamB":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'TOTAL DISCHARGES TO STREAM B', 'DISCHARGES TO STREAM B - BASIS OF ESTIMATE']
"streamC":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'TOTAL DISCHARGES TO STREAM C', 'DISCHARGES TO STREAM C - BASIS OF ESTIMATE']
"streamD":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'TOTAL DISCHARGES TO STREAM D', 'DISCHARGES TO STREAM D - BASIS OF ESTIMATE']
"streamE":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'TOTAL DISCHARGES TO STREAM E', 'DISCHARGES TO STREAM E - BASIS OF ESTIMATE']
"streamF":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'TOTAL DISCHARGES TO STREAM F', 'DISCHARGES TO STREAM F - BASIS OF ESTIMATE']
"onsiteland":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'TOTAL LAND TREATMENT', 'LAND TRTMT/APPL FARMING - BASIS OF ESTIMATE']
"onsiteother":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'TOTAL OTHER DISPOSAL', 'OTHER DISPOSAL -BASIS OF ESTIMATE']
"offsiteland":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'LAND TREATMENT']
"offsiteother":['TRIFID', 'FACILITY STATE', 'PRIMARY NAICS CODE', 'CAS NUMBER', 'UNIT OF MEASURE', 'OTHER LAND DISPOSAL']

TRI table after step 1 of formatting.

In [20]:
tri1.head(10)

,Amount,Basis of Estimate,FacilityID,NAICS,OriginalFlowID,Source,State,Unit
0,5.0,E1,7910WCSTLC3SART,424690,000107211,fug,TX,Pounds
1,5.0,E1,7127WCSTLC17IND,424690,000111422,fug,LA,Pounds
2,15.0,E1,7806WCSTLC1819F,213112,000091203,fug,TX,Pounds
3,5.0,E1,7770WCSTLC6534I,424690,000092524,fug,TX,Pounds
4,15.0,E1,7770WCSTLC6534I,424690,000107211,fug,TX,Pounds
5,0.0,NaN,06382MNTVL74LAT,221112,000191242,fug,CT,Pounds
6,0.0,NaN,06382MNTVL74LAT,221112,N590,fug,CT,Pounds
7,0.0,NaN,15095TRCTHCRANB,332321,N120,fug,PA,Pounds
8,32.0,C,15095TRCTHCRANB,332321,001330207,fug,PA,Pounds
9,0.0,NaN,27298DWRDS323ST,321920,N420,fug,NC,Pounds

TRI table after step 2 of formatting.

In [21]:
tri2.head(10)

,Amount,FacilityID,NAICS,OriginalFlowID,Source,State,Unit,DQI Reliability Score
0,5.0,7910WCSTLC3SART,424690,000107211,fug,TX,Pounds,2.0
1,5.0,7127WCSTLC17IND,424690,000111422,fug,LA,Pounds,2.0
2,15.0,7806WCSTLC1819F,213112,000091203,fug,TX,Pounds,2.0
3,5.0,7770WCSTLC6534I,424690,000092524,fug,TX,Pounds,2.0
4,15.0,7770WCSTLC6534I,424690,000107211,fug,TX,Pounds,2.0
5,0.0,06382MNTVL74LAT,221112,000191242,fug,CT,Pounds,5.0
6,0.0,06382MNTVL74LAT,221112,N590,fug,CT,Pounds,5.0
7,0.0,15095TRCTHCRANB,332321,N120,fug,PA,Pounds,5.0
8,32.0,15095TRCTHCRANB,332321,001330207,fug,PA,Pounds,3.0
9,0.0,27298DWRDS323ST,321920,N420,fug,NC,Pounds,5.0

TRI table after step 3 of formatting.

In [22]:
tri3.head(10)

,FacilityID,NAICS,OriginalFlowID,Source,State,ReliabilityScore,Context,Amount
0,7910WCSTLC3SART,424690,000107211,fug,TX,2.0,air,2.267962
1,7127WCSTLC17IND,424690,000111422,fug,LA,2.0,air,2.267962
2,7806WCSTLC1819F,213112,000091203,fug,TX,2.0,air,6.803886
3,7770WCSTLC6534I,424690,000092524,fug,TX,2.0,air,2.267962
4,7770WCSTLC6534I,424690,000107211,fug,TX,2.0,air,6.803886
5,06382MNTVL74LAT,221112,000191242,fug,CT,5.0,air,0.000000
6,06382MNTVL74LAT,221112,N590,fug,CT,5.0,air,0.000000
7,15095TRCTHCRANB,332321,N120,fug,PA,5.0,air,0.000000
8,15095TRCTHCRANB,332321,001330207,fug,PA,3.0,air,14.514957
9,27298DWRDS323ST,321920,N420,fug,NC,5.0,air,0.000000

Final TRI output. Verify that it is in the standard format.

In [23]:
tri.head(10)

,OriginalFlowID,Context,Amount,State,NAICS,FacilityID,ReliabilityScore,Source
0,000107211,air,2.267962,TX,424690,7910WCSTLC3SART,2.0,fug
1,000111422,air,2.267962,LA,424690,7127WCSTLC17IND,2.0,fug
2,000091203,air,6.803886,TX,213112,7806WCSTLC1819F,2.0,fug
3,000092524,air,2.267962,TX,424690,7770WCSTLC6534I,2.0,fug
4,000107211,air,6.803886,TX,424690,7770WCSTLC6534I,2.0,fug
5,000191242,air,0.000000,CT,221112,06382MNTVL74LAT,5.0,fug
6,N590,air,0.000000,CT,221112,06382MNTVL74LAT,5.0,fug
7,N120,air,0.000000,PA,332321,15095TRCTHCRANB,5.0,fug
8,001330207,air,14.514957,PA,332321,15095TRCTHCRANB,3.0,fug
9,N420,air,0.000000,NC,321920,27298DWRDS323ST,5.0,fug